@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Sep 21 21:06:15 +0300 2025
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim or4_behav -key {Behavioral:sim_1:Functional:or4} -tclbatch or4.tcl -view D:/university/learn_hardware/vhdl_basics/simulation.cfg/or4_behav.wcfg -view D:/university/learn_hardware/vhdl_basics/simulation.cfg/comb_behav.wcfg -view D:/university/learn_hardware/vhdl_basics/simulation.cfg/mux4_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
